version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9086:9090
    command:
    - --config.file=/home/ubuntu/prometheus/prometheus.yml
    volumes:
    - /home/ubuntu/prometheus/prometheus.yml:/home/ubuntu/prometheus/prometheus.yml:ro
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
    - 9087:9100
    user: "root"