version: '3.2'
services:
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
    - 3000:3000
    user: "root"
